---
- name: Install Ansible roles from requirements.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles from requirements.yml
      command: ansible-galaxy install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"

- name: role demo
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: lucab85.ansible_role_log4shell
      detector_path: "/var"
      verify_gpg: false
