---
- name: modprobe module demo
  hosts: localhost
  become: true
  vars:
    module_name: "dummy"
    ansible_connection: local
  gather_facts: false
  tasks:
    - name: load the module
      community.general.modprobe:
        name: "{{ module_name }}"
        state: present
